# Configuration for the database. Default configuration for a 
# MySQL2 setup shown below.
#
# Refer to ActiveRecord::Base.establish_connection for additional
# configuration options
database:
  adapter: mysql2
  encoding: utf8
  host: localhost
  port: 5432
  database: sfopticon
  socket:
  username: root
  password: 
  flags:

scm:
  adapter: github
  url: https://github.com/
  username: 
  password: 
  local_path: orgs
  options: # Options specific to this adapter
    description:
    homepage:
    private: true
    has_issues:
    has_wiki:
    has_downloads:
    organization:
    team_id:
    gitignore_template:

test:
  username: 
  password: 

logging:
  logdev: STDERR
  level: DEBUG
  shift_age: 10
  shift_size: 1048576
  datetime_format:

# Set "test" to true, to allow logging into test.salesforce.com for your "production" env
salesforce:
  test: false
  metadata_types:
    - ApexClass
    - ApexComponent
    - ApexPage
    - ApexTrigger
