# Configuration for the database. Default configuration for a 
# MySQL2 setup shown below.
#
# Refer to ActiveRecord::Base.establish_connection for additional
# configuration options
database:
  adapter: mysql2
  encoding: utf8
  database: opticon
  username: root
  password:

scm:
  adapter: github
  url:
  username:
  password:
  local_path: orgs
  options: # Options specific to this adapter
    description:
    homepage:
    private: true
    has_issues:
    has_wiki:
    has_downloads:
    organization:
    team_id:
    auto_init:
    gitignore_template:

logging:
  logdev: debug_log.txt
  level: DEBUG
  shift_age: 10
  shift_size: 1048576
  datetime_format:

